version: '3'

services:
  user_profile_backend:
    build:
      context: ./backend/user_profile_backend
    environment:
      USER_HOST: http://user_profile_backend:4000/api/users
    ports: 
      - 4000:4000
  
  question-backend:
    build:
      context: ./backend/question-backend
    environment:
      USER_HOST: http://user_profile_backend:4000/api/users
    ports: 
      - 8000:8000
    depends_on:
      - user_profile_backend

  frontend:
    build:
      context: ./frontend
    ports: 
      - 3000:3000
    environment: 
      USER_HOST: http://user_profile_backend:4000/api/users
      QUESTION_HOST: http://question-backend:8000/api/questions

    depends_on:
      - user_profile_backend
      - question-backend