# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: user_profile_backend CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

defaults:
  run:
    working-directory: backend/user_profile_backend

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend
        uses: actions/checkout@v3

      # - run: npm ci
      # - run: npm run build --if-present
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm install mocha chai sinon --save-dev
          npm install --save-dev nyc
        working-directory: backend/user_profile_backend
        
      - name: Run Tests with Coverage
        run: npm run test-with-coverage
        continue-on-error: true

      - name: Check Test Status and Prevent Merge
        run: |
          if [ ${{ job.status }} == "failure" ]; then
            echo "Tests failed, preventing merge."
            exit 1
          else
            echo "Tests passed, merge can proceed."
          fi
